import type { InsightsTabEntry, InsightsTabId } from "../../shared/api";

/**
 * Per-tab curated ticker universes.
 *
 * Why server-side: a single source of truth for "what counts as trending / AI /
 * cloud", easy to edit without rebuilding the client, and the client can fetch the
 * latest universe via /api/insights-tab?tab=… without a hard import.
 *
 * The client overlays LIVE prices via `useBatchQuotes(symbols)` so even when
 * upstream screener endpoints are dead (the FMP `/stable/gainers`, `/actives`,
 * `/sectors-performance` paths 404 on current keys) the cards still show real
 * intraday prices — the universe names just stay curated.
 */
export const insightsTabUniverses: Record<InsightsTabId, InsightsTabEntry[]> = {
  sp500: [
    { symbol: "NVDA", name: "Nvidia Corp", sector: "Technology" },
    { symbol: "AAPL", name: "Apple Inc", sector: "Technology" },
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "AMZN", name: "Amazon.com Inc", sector: "Consumer Cyclical" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
    { symbol: "AVGO", name: "Broadcom Inc", sector: "Technology" },
    { symbol: "GOOG", name: "Alphabet Inc Class C", sector: "Communication Services" },
    { symbol: "META", name: "Meta Platforms Inc Class A", sector: "Communication Services" },
    { symbol: "TSLA", name: "Tesla Inc", sector: "Consumer Cyclical" },
    { symbol: "BRKA", name: "Berkshire Hathaway Inc Class B", sector: "Financial Services" },
    { symbol: "MU", name: "Micron Technology Inc", sector: "Technology" },
    { symbol: "LLY", name: "Eli Lilly + Co", sector: "Healthcare" },
    { symbol: "JPM", name: "JPMorgan Chase + Co", sector: "Financial Services" },
    { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
    { symbol: "XOM", name: "Exxon Mobil Corp", sector: "Energy" },
    { symbol: "INTC", name: "Intel Corp", sector: "Technology" },
    { symbol: "JNJ", name: "Johnson + Johnson", sector: "Healthcare" },
    { symbol: "V", name: "Visa Inc Class A", sector: "Financial Services" },
    { symbol: "WMT", name: "Walmart Inc", sector: "Consumer Defensive" },
    { symbol: "CSCO", name: "Cisco Systems Inc", sector: "Technology" },
    { symbol: "COST", name: "Costco Wholesale Corp", sector: "Consumer Defensive" },
    { symbol: "CAT", name: "Caterpillar Inc", sector: "Industrials" },
    { symbol: "NFLX", name: "Netflix Inc", sector: "Communication Services" },
    { symbol: "CVX", name: "Chevron Corp", sector: "Energy" },
    { symbol: "UNH", name: "UnitedHealth Group Inc", sector: "Healthcare" },
    { symbol: "BAC", name: "Bank Of America Corp", sector: "Financial Services" },
    { symbol: "AMAT", name: "Applied Materials Inc", sector: "Technology" },
    { symbol: "PG", name: "Procter + Gamble Co", sector: "Consumer Defensive" },
    { symbol: "ORCL", name: "Oracle Corp", sector: "Technology" },
    { symbol: "ABBV", name: "AbbVie Inc", sector: "Healthcare" },
    { symbol: "KO", name: "Coca-Cola Co", sector: "Consumer Defensive" },
    { symbol: "PLTR", name: "Palantir Technologies Inc A", sector: "Technology" },
    { symbol: "HD", name: "Home Depot Inc", sector: "Consumer Cyclical" },
    { symbol: "GE", name: "General Electric", sector: "Industrials" },
  ],
  trending: [
    { symbol: "NVDA", name: "Nvidia Corp", sector: "Technology" },
    { symbol: "TSLA", name: "Tesla Inc", sector: "Consumer Cyclical" },
    { symbol: "AAPL", name: "Apple Inc", sector: "Technology" },
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "META", name: "Meta Platforms Inc Class A", sector: "Communication Services" },
    { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
    { symbol: "PLTR", name: "Palantir Technologies Inc A", sector: "Technology" },
    { symbol: "AVGO", name: "Broadcom Inc", sector: "Technology" },
    { symbol: "COST", name: "Costco Wholesale Corp", sector: "Consumer Defensive" },
    { symbol: "NFLX", name: "Netflix Inc", sector: "Communication Services" },
    { symbol: "AMZN", name: "Amazon.com Inc", sector: "Consumer Cyclical" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
  ],
  growth: [
    { symbol: "NVDA", name: "Nvidia Corp", sector: "Technology" },
    { symbol: "META", name: "Meta Platforms Inc Class A", sector: "Communication Services" },
    { symbol: "AVGO", name: "Broadcom Inc", sector: "Technology" },
    { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
    { symbol: "AAPL", name: "Apple Inc", sector: "Technology" },
    { symbol: "AMZN", name: "Amazon.com Inc", sector: "Consumer Cyclical" },
    { symbol: "CRM", name: "Salesforce Inc", sector: "Technology" },
    { symbol: "SHOP", name: "Shopify Inc", sector: "Technology" },
    { symbol: "NOW", name: "ServiceNow Inc", sector: "Technology" },
    { symbol: "PANW", name: "Palo Alto Networks Inc", sector: "Technology" },
  ],
  dividend: [
    { symbol: "JNJ", name: "Johnson + Johnson", sector: "Healthcare" },
    { symbol: "KO", name: "Coca-Cola Co", sector: "Consumer Defensive" },
    { symbol: "PG", name: "Procter + Gamble Co", sector: "Consumer Defensive" },
    { symbol: "PEP", name: "PepsiCo Inc", sector: "Consumer Defensive" },
    { symbol: "V", name: "Visa Inc Class A", sector: "Financial Services" },
    { symbol: "WMT", name: "Walmart Inc", sector: "Consumer Defensive" },
    { symbol: "XOM", name: "Exxon Mobil Corp", sector: "Energy" },
    { symbol: "CVX", name: "Chevron Corp", sector: "Energy" },
    { symbol: "ABBV", name: "AbbVie Inc", sector: "Healthcare" },
    { symbol: "MRK", name: "Merck + Co Inc", sector: "Healthcare" },
    { symbol: "HD", name: "Home Depot Inc", sector: "Consumer Cyclical" },
    { symbol: "LOW", name: "Lowes Companies Inc", sector: "Consumer Cyclical" },
  ],
  buyback: [
    { symbol: "AAPL", name: "Apple Inc", sector: "Technology" },
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
    { symbol: "META", name: "Meta Platforms Inc Class A", sector: "Communication Services" },
    { symbol: "ORCL", name: "Oracle Corp", sector: "Technology" },
    { symbol: "AMAT", name: "Applied Materials Inc", sector: "Technology" },
    { symbol: "V", name: "Visa Inc Class A", sector: "Financial Services" },
    { symbol: "MA", name: "Mastercard Inc Class A", sector: "Financial Services" },
    { symbol: "LRCX", name: "Lam Research Corp", sector: "Technology" },
    { symbol: "HPQ", name: "HP Inc", sector: "Technology" },
  ],
  ai: [
    { symbol: "NVDA", name: "Nvidia Corp", sector: "Technology" },
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
    { symbol: "META", name: "Meta Platforms Inc Class A", sector: "Communication Services" },
    { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
    { symbol: "AVGO", name: "Broadcom Inc", sector: "Technology" },
    { symbol: "PLTR", name: "Palantir Technologies Inc A", sector: "Technology" },
    { symbol: "SNOW", name: "Snowflake Inc", sector: "Technology" },
    { symbol: "CRWD", name: "CrowdStrike Holdings Inc", sector: "Technology" },
    { symbol: "PANW", name: "Palo Alto Networks Inc", sector: "Technology" },
    { symbol: "NOW", name: "ServiceNow Inc", sector: "Technology" },
    { symbol: "AI", name: "C3.ai Inc", sector: "Technology" },
  ],
  cloud: [
    { symbol: "MSFT", name: "Microsoft Corp", sector: "Technology" },
    { symbol: "AMZN", name: "Amazon.com Inc", sector: "Consumer Cyclical" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Communication Services" },
    { symbol: "CRM", name: "Salesforce Inc", sector: "Technology" },
    { symbol: "NOW", name: "ServiceNow Inc", sector: "Technology" },
    { symbol: "SNOW", name: "Snowflake Inc", sector: "Technology" },
    { symbol: "DDOG", name: "Datadog Inc", sector: "Technology" },
    { symbol: "NET", name: "Cloudflare Inc", sector: "Technology" },
    { symbol: "ZS", name: "Zscaler Inc", sector: "Technology" },
    { symbol: "CRWD", name: "CrowdStrike Holdings Inc", sector: "Technology" },
    { symbol: "OKTA", name: "Okta Inc", sector: "Technology" },
    { symbol: "ADBE", name: "Adobe Inc", sector: "Technology" },
  ],
  ev: [
    { symbol: "TSLA", name: "Tesla Inc", sector: "Consumer Cyclical" },
    { symbol: "RIVN", name: "Rivian Automotive Inc", sector: "Consumer Cyclical" },
    { symbol: "F", name: "Ford Motor Co", sector: "Consumer Cyclical" },
    { symbol: "GM", name: "General Motors Co", sector: "Consumer Cyclical" },
    { symbol: "NIO", name: "NIO Inc", sector: "Consumer Cyclical" },
    { symbol: "XPEV", name: "XPeng Inc", sector: "Consumer Cyclical" },
    { symbol: "LI", name: "Li Auto Inc", sector: "Consumer Cyclical" },
    { symbol: "BYD", name: "BYD Co Ltd", sector: "Consumer Cyclical" },
    { symbol: "STLA", name: "Stellantis NV", sector: "Consumer Cyclical" },
    { symbol: "LCID", name: "Lucid Group Inc", sector: "Consumer Cyclical" },
  ],
  leisure: [
    { symbol: "DIS", name: "Walt Disney Co", sector: "Communication Services" },
    { symbol: "NFLX", name: "Netflix Inc", sector: "Communication Services" },
    { symbol: "CMCSA", name: "Comcast Corp", sector: "Communication Services" },
    { symbol: "PARA", name: "Paramount Global Class B", sector: "Communication Services" },
    { symbol: "ROKU", name: "Roku Inc", sector: "Communication Services" },
    { symbol: "MTN", name: "Vail Resorts Inc", sector: "Consumer Cyclical" },
    { symbol: "MAR", name: "Marriott International Inc", sector: "Consumer Cyclical" },
    { symbol: "H", name: "Hyatt Hotels Corp", sector: "Consumer Cyclical" },
    { symbol: "AAL", name: "American Airlines Group Inc", sector: "Industrials" },
    { symbol: "UAL", name: "United Airlines Holdings Inc", sector: "Industrials" },
    { symbol: "BKNG", name: "Booking Holdings Inc", sector: "Consumer Cyclical" },
    { symbol: "ABNB", name: "Airbnb Inc", sector: "Consumer Cyclical" },
  ],
};
